#!/bin/bash
# build_app.sh — packages ToMd as a real macOS Application so you can
# launch it from Spotlight (Cmd+Space, type "ToMd", hit Enter) instead
# of ever touching Terminal or "running the .py script" again.
#
# Run this ONCE on your Mac, from this folder:
#   chmod +x build_app.sh && ./build_app.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="ToMd"
BUILD_DIR="$HERE/build"
APP_PATH="$BUILD_DIR/${APP_NAME}.app"
DEST="$HOME/Applications"
BIN_DIR="$HOME/.local/bin"

# Interpreter to bake into the app + CLI launcher. Using the python3 that is
# active *right now* (e.g. the venv you installed requirements into) means the
# app always has the same packages you just installed — and a working Tk — so
# it never silently falls back to a stale system python3.
PYBIN="$(python3 -c 'import sys; print(sys.executable)')"

echo "🔧 Building ${APP_NAME}.app ..."
echo "🐍 Using interpreter: $PYBIN"
mkdir -p "$BUILD_DIR"
rm -rf "$APP_PATH"

# 1. Compile a tiny AppleScript launcher into an .app bundle.
#    It finds its own location at runtime and runs the bundled python files
#    from there, so the app is fully self-contained and relocatable.
cat > "$BUILD_DIR/launcher.applescript" <<APPLESCRIPT
on run
    set appPosixPath to POSIX path of (path to me)
    set scriptPath to appPosixPath & "Contents/Resources/app_gui.py"
    try
        do shell script "${PYBIN} " & quoted form of scriptPath
    on error errMsg number errNum
        if errNum is not -128 then
            display alert "ToMd hit a snag" message errMsg
        end if
    end try
end run
APPLESCRIPT

osacompile -o "$APP_PATH" "$BUILD_DIR/launcher.applescript"

# 2. Drop the real python source into Contents/Resources so the launcher
#    can find it, and Spotlight sees one tidy .app.
cp "$HERE/app_gui.py" "$APP_PATH/Contents/Resources/"
cp "$HERE/converter_core.py" "$APP_PATH/Contents/Resources/"

# 3. Make it a background-only app (no Dock icon needed since it's a
#    quick utility) — optional, comment out if you'd rather see it in the Dock.
PLIST="$APP_PATH/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :CFBundleName string ${APP_NAME}" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string ${APP_NAME}" "$PLIST" 2>/dev/null || true

# 4. Install into ~/Applications so Spotlight indexes it immediately.
mkdir -p "$DEST"
rm -rf "$DEST/${APP_NAME}.app"
cp -R "$APP_PATH" "$DEST/"

# 5. Install a `ToMD` terminal command so you can launch from any shell by
#    just typing its name. It runs the same interpreter the app was built with.
mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/ToMD"
APP_SCRIPT="$DEST/${APP_NAME}.app/Contents/Resources/app_gui.py"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# Auto-generated by build_app.sh — launches ToMd with the interpreter it was
# built with, so bundled dependencies are always on hand.
exec "${PYBIN}" "${APP_SCRIPT}" "\$@"
LAUNCH
chmod +x "$LAUNCHER"
echo "✅ Installed 'ToMD' command to $LAUNCHER"

# 6. Make sure ~/.local/bin is on PATH for future shells.
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;  # already on PATH — nothing to do
    *)
        if [ -e "$HOME/.zshrc" ] || [ ! -e "$HOME/.bashrc" ]; then
            RCFILE="$HOME/.zshrc"
        else
            RCFILE="$HOME/.bashrc"
        fi
        echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$RCFILE"
        echo "ℹ️  Added $BIN_DIR to PATH in $RCFILE — run 'source $RCFILE' (or open a new terminal)."
        ;;
esac

echo "✅ Installed to $DEST/${APP_NAME}.app"
echo ""
echo "Launch it any of these ways:"
echo "  • Terminal:  ToMD        (may need a new shell / 'source' first)"
echo "  • Spotlight: Cmd+Space, type 'ToMd', Enter"
echo "  • Finder:    open -a ToMd"
